# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          # install program and requirements for dev
          - pip install .
          - pip install -r requirements-dev.txt
          # Run the tests and check for test coverage.
          - coverage run -m pytest
          # Generate test coverage report.
          - coverage report -m
          # Upload the report to codecov.
          - codecov
          # Enforce code style (but relax line length limit a bit).
          - flake8 --max-line-length=115
          # Build the documentation.
          - make -C docs html
          # Run the ieee14_syn.dm tds
          - andes cases/ieee14/ieee14_syn.dm -r tds -v 10 --no-output --tf 0.1
